stages:
  - build

build_docker:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    CI_REGISTRY: "registry.opencode.de"
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/oc000161649365/gratulationsdienst:latest .
    - docker push $CI_REGISTRY/oc000161649365/gratulationsdienst:latest
  only:
    - main