stages:
  - build

build_docker:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"registry.opencode.de\":{\"username\":\"$CI_DEPLOY_USER\",\"password\":\"$CI_DEPLOY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context /builds/oc000161649365/Gratulationsdienst
      --dockerfile /builds/oc000161649365/Gratulationsdienst/docker/Dockerfile
      --destination registry.opencode.de/oc000161649365/gratulationsdienst:latest
  only:
    - main