name: gratulationsdienst

services:
  # 1. PHP & Apache Webserver
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: php_webserver
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ../php-api:/var/www/html/gratulationsdienst/php-api
    depends_on:
      - db

  # 2. MariaDB Datenbank-Server
  db:
    image: mariadb:11
    container_name: mariadb_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: test123456!!
      MARIADB_DATABASE: gratulationsdienst
      MARIADB_USER: eb
      MARIADB_PASSWORD: test123456!!
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  # 3. phpMyAdmin Web-Oberfläche
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_web
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"

volumes:
  mariadb_data:
